version: "3.8"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_HOST: report-database
      VALIDATION_HOST: manager

  manager:
    build:
      context: identityManager
      dockerfile: Dockerfile.manager
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      DB_HOST_PG: db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      API_URL: backend

  report-database:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf
      - mongo-data:/data/db  # Mount for database data
      - mongo-logs:/var/log/mongodb  # Mount for logs
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Replace with your MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: mavericks123  # Replace with your MongoDB root password
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]

  db:
    image: postgres:latest
    container_name: my_postgres2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin_user  # Replace with your PostgreSQL username
      POSTGRES_PASSWORD: maverickspostgres123  # Replace with your PostgreSQL password
    ports:
      - "32701:5432"  # Maps host port 32701 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Named volume for PostgreSQL data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Optional: Initialization SQL script
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:  # Named volume for MongoDB data
  mongo-logs:  # Named volume for MongoDB logs
  pgdata:  # Named volume for PostgreSQL data
