version: "3.8"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_HOST: report-database
      VALIDATION_HOST: manager
      

  manager:
    build:
      context: identityManager
      dockerfile: Dockerfile.manager
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      DB_HOST_PG: db 


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      API_URL: backend


  report-database:
    image: mongo
    container_name: mongo
    volumes:
      - database:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: my_postgres2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: mynewuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "32701:5432" # Maps host port 32700 to container port 5432
    volumes:
      - pgdata_0:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database:
  pgdata_0:
