spring.application.name=Backend
spring.data.mongodb.host=${DB_HOST}
spring.data.mongodb.port=27017
server.port=8080
spring.data.mongodb.uri=mongodb://admin:mavericks123@${DB_HOST}:27017/LGApp?authSource=admin
spring.data.mongodb.database=LGApp
validation.uri=${VALIDATION_HOST}

# spring.application.name=Backend
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# server.port=8090
# spring.data.mongodb.uri=mongodb://localhost:27017/LGApp
# spring.data.mongodb.database=LGApp